#!/bin/bash

# set local_file [lindex $argv 0]
# set remote_path [lindex $argv 1]
project=$(pwd |cut -d / -f 4-)

echo "Current work path: "
echo "      "$project
echo "Remote_path:"
echo "      "$HOMESSH'/home/Data/myj/'$project
echo "Help: "
echo "    Info: this tool only use for remote and locate project  has the same path"
echo "    For multiply files use: '{file1,file2,..}'"
echo "    or use regix express: 'test*' "
echo $*
echo  "$HOMESSH/home/Data/myj/$project/$*" 
if [ $# -eq 1 ]
then
  scp  "$HOMESSH/home/Data/myj/$project/$*" ./
else
  scp -r "$HOMESSH/home/Data/myj/$project/$2" ./
fi
