#!/usr/bin/env bash
"""
    Date: 2019-03-19
    Author: Maoyanjun
    Email: maoyanjun_dut@foxmail.com
    HomePage: http://maoyanjun.top
    LastChange: 2019-03-19 09:55:38
    History:
    Discription: 
    Copyright: GNU General Public License
"""
# first need to prepare the surfaceElevationAnyName_sets,sampleDict_p_alpha and sampleDict_U files under the system dir,
#the sampleDict_U can be modified from sampleDict_p_alpha file by just rewrite the key word p and alpha.water to U in the fields zone 
# the surfaceElevationAnyName_sets file can be generated by the waveGaugesNProbes preprossing utility which is only aviable with the proper installation of waves2foam toolbox with given probeDefinitions under the constant dir
# the definitions of the probes can be set in the probeDefinitions dict

rm -r postProcessing

mv ./sytem/sampleDict_p_alpha ./system/sampleDict

runApplication sample

mv postProcessing postProcessing2

mv ./system/sampleDict_U ./system/sampleDict

runApplication sample

python IntergateU.py

